python  LSP_train-bpe-cn.py \
    --train_input_file /home/Public/data/transfer-learning/output/output-qa/xinli001_jiandanxinli-qa.topics_去重_DialogGPT-GPT2BPETokenizer_CN_32K_v3_2_BPE_db \
    --eval_input_file /home/Public/data/transfer-learning/output/output-qa/xinli001_jiandanxinli-qa.topics_去重_DialogGPT/valid_0_DialogGPT.tsv \
    --output_dir ./output_model/345m-hmwebmix-bpe-v3.2 \
    --model_name_or_path ./pre-train-345m-hmwebmix-bpe-v3.2 \
    --init_checkpoint ./pre-train-345m-hmwebmix-bpe-v3.2/pytorch_model.bin \
    --learning_rate 1e-4  \
    --train_batch_size 4 \
    --eval_batch_size 4 \
    --no_token_id False \
    --valid_step 100
